### ISSUE TITLE
Add Tasks model

### ISSUE THREAD

**Issue by TaTooKa** [manuelsoldini/aws-demo#12]
the tasks must have a priority, an assignment, and operator (user)
- Admin must be able to add/modify/remove Tasks

**Comment by nicosarubbi** [comment]
**Task fields:**
priority: int (min 0, max 5)
type: char[2], {PI: PICK, CO: COUNT}
from: FK to Location
to: FK to Location
quantity: int
datetime: datetime
status: char[2], {PE: PENDING, IP: "IN PROGRESS", CO: COMPLETED, DO: DONE, BA: BACK, CA: CANCELED}
operator: FK to User
comment: text

**Methods:**
pending_queue(operator=None): _Returns a list of tasks with status=PENDING. If an operator is given, return only the tasks for him._

completed_queue(): Returns a list of tasks with status=COMPLETED.

**Comment by nicosarubbi** [comment]
- Please add checks for datetime None in the method datetimeToShow
- Please add checks for empty queue in the methods.
