### ISSUE TITLE
API Services for Tasks

### ISSUE THREAD

**Issue by TaTooKa** [manuelsoldini/aws-demo#7]
make sure that some of the fields are readonly.

**Comment by nicosarubbi** [comment]
**Create three API calls.**
- GET /task/<id> : Returns one task by _<id>_. (only if the task is assigned to the user, or the user is admin).
- POST /task/<id> : Takes status, quantity and comment, and updates the task by _<id>_ (only if the task is assigned to the user, or the user is admin).
- GET /pendingtask/ Calls to the method Task.assign_task(operator), and returns the task (if any).

**Comment by TaTooKa** [comment]
# aws-demo API doc

## POST http://127.0.0.1:8000/api-token-auth/

returns a token to use in the following API calls.
requires **username** and **password** fields.

all the following calls require the token in the header, in the following format:
`Authorization: Token fb7e9d5513dea3a7c9da3010876f939436c2ede4`

## GET http://127.0.0.1:8000/task/1/

returns a single task by ID.

## PUT http://127.0.0.1:8000/task/1/

updates a single task, by ID. Modifiable fields: 
- status ("BA" or "CO")
- comment (string)
- quantity (integer)

## GET http://127.0.0.1:8000/operator/

returns operator data (name, username, email)

## GET http://127.0.0.1:8000/pendingtask/

returns a task with status **IN_PROGRESS** for the current user, ordered by priority and datetime.
If no tasks are IN_PROGRESS, a call to **Task.assign_task** puts a new task from PENDING to IN_PROGRESS.
